update to version 3.4.1

diff --git a/examples/test b/examples/test
--- a/examples/test
+++ b/examples/test
@@ -1,6 +1,6 @@
 #! /bin/sh
 
-# Copyright (C) 2005-2015 Free Software Foundation, Inc.
+# Copyright (C) 2005-2015, 2018-2019 Free Software Foundation, Inc.
 #
 # This program is free software: you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -15,7 +15,11 @@
 # You should have received a copy of the GNU General Public License
 # along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-me=`basename $1 .test`
+SHELL=/bin/sh
+export SHELL
+
+me=$(basename "$1" .test)
+medir=$(dirname "$1" | sed -e 's,.*examples/,,')
 
 # Number of the current test.
 number=1
@@ -23,17 +27,33 @@ number=1
 # Exit status of this script.
 exit=true
 
-# top_buiddir.
-cwd=`pwd`
+# top_builddir.
+cwd=$(pwd)
 
 # The exercised program.
-prog=$cwd/examples/$me/$me
+for p in "$cwd/examples/$medir/$me"
+do
+    if test -x "$p"; then
+        prog=$p
+        break
+    elif test -f "$p.class"; then
+        pwd
+        prog="$SHELL $cwd/javaexec.sh -cp $(dirname $p) $(basename $p)"
+        break
+    fi
+done
+if test x"$prog" = x; then
+    echo "$me: ERROR: cannot find program to exercise in:"
+    echo "$me: ERROR:   $cwd/examples/$medir/$me"
+    exit 1
+fi
+
 
 # cleanup
 # -------
 cleanup ()
 {
-  local status=$?
+  status=$?
   if test -z "$DEBUG"; then
      cd $cwd
      rm -rf $$.dir
@@ -44,33 +64,41 @@ trap cleanup 0 1 2 13 15
 mkdir $$.dir
 cd $$.dir
 
-# run EXPECTED-EXIT-STATUS EXPECTED-OUTPUT [PARSER-OPTIONS]
-# ---------------------------------------------------------
+# run [-noerr] EXPECTED-EXIT-STATUS EXPECTED-OUTPUT [PARSER-OPTIONS]
+# ------------------------------------------------------------------
+# -noerr: ignore stderr, otherwise merge it into effective output.
 run ()
 {
+  noerr=false
+  case $1 in
+    (-noerr) noerr=true; shift;;
+  esac
+
   # Expected exit status.
-  local sta_exp=$1
+  sta_exp=$1
   shift
   # Expected output.
-  local out_exp=$1
+  out_exp=$1
   shift
   # Effective exit status.
-  local sta_eff=0
-  $prog "$@" - <input >out_eff || sta_eff=$?
-  # Effective output.
-  local out_eff=`cat out_eff`
+  sta_eff=0
+  $prog "$@" - <input >out_eff 2>err_eff || sta_eff=$?
+  # Combine effective output and error streams.
+  out_eff=$(cat out_eff && $noerr || sed -e 's/^/err: /g' err_eff)
   if test $sta_eff -eq $sta_exp; then
     if test "$out_eff" = "$out_exp"; then
       echo "$me: PASS: $number"
     else
       echo "$me: FAIL: $number (expected output: $out_exp, effective: $out_eff)"
+      cat err_eff
       exit=false
     fi
   else
     echo "$me: FAIL: $number (expected status: $sta_exp, effective: $sta_eff)"
+    cat err_eff
     exit=false
   fi
-  number=`expr $number + 1`
+  number=$(expr $number + 1)
 }
 
 # We have cd'd one level deeper.
